### ISSUE TITLE
Support for 3d party middleware

### ISSUE THREAD

**Issue by almarklein** [almarklein/asgish#20]
It looks like [Starlette's](https://www.starlette.io/middleware/) middleware that is designed to be framework agnostic. It would be interesting to see if we can fit that in Asgish somehow. Perhaps @tomchristie has some remarks/tips?

**Comment by tomchristie** [comment]
See https://www.starlette.io/middleware/#using-asgi-middleware-without-starlette

Example:

```
import asgish
from starlette.middleware.trustedhost import TrustedHostMiddleware

@asgish.to_asgi
async def main(request):
    return f"<html>You requested <b>{request.path}</b></html>"

main = TrustedHostMiddleware(main, allowed_hosts=['example.com'])

if __name__ == '__main__':
    asgish.run(main, 'uvicorn', 'localhost:8080')
```

**Comment by tomchristie** [comment]
In starlette we also add some syntactic sugar if you're adding middleware to an `Starlette` application instance, so we have...

```
app = Starlette()
app.add_middleware(TrustedHostMiddleware, allowed_hosts=['example.com'])
```

You could do something similar in asgish if you wanted, eg...

import asgish
from starlette.middleware.trustedhost import TrustedHostMiddleware

@asgish.middleware(TrustedHostMiddleware, allowed_hosts=['example.com'])
@asgish.to_asgi
async def main(request):
    return f"<html>You requested <b>{request.path}</b></html>"

if __name__ == '__main__':
    asgish.run(main, 'uvicorn', 'localhost:8080')

**Comment by almarklein** [comment]
Thanks for that! I will have a stab at this soon :)

**Comment by almarklein** [comment]
This was easy: https://github.com/almarklein/asgish/blob/master/examples/example_middleware.py

**Comment by tomchristie** [comment]
👍
