### ISSUE TITLE
Rename handler2asgi?

### ISSUE THREAD

**Issue by almarklein** [almarklein/asgish#6]
I find that name rather ugly. Though it's explicit and clear...

Options:

* Keep as is: clear but ugly
* `handler_to_asgi`: possibly more ugly
* `application` :/
* `make_asgi` / `to_asgi`
* ...

**Comment by zhangkaizhao** [comment]
Or `asgify`? More short...

**Comment by almarklein** [comment]
Went with `to_asgi`
